sass:
  sass_dir: assets/css

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Stefan Hengl" # the name of your site, e.g. ACME Corp.
